version: '3'
services:
  dask-worker:
    build: ./images/dask-worker
  dask-scheduler:
    build: ./images/dask-scheduler
    ports: ["8787:8787", "8788:8788"]
  notebook:
    build: ./images/notebook
    ports: ['8888:8888']
    volumes:
      - notebooks:/opt/notebooks

volumes:
  notebooks: